name: Build C/C++ CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Clone garrysmod_common
      run: |
        git clone --recursive https://github.com/danielga/garrysmod_common.git garrysmod_common

    - name: Patch garrysmod_common
      run: |
        $content = Get-Content garrysmod_common/premake/generator.lua
        $content = $content -replace "multiprocessorcompile", "-- multiprocessorcompile"
        $content = $content -replace "linktimeoptimization", "-- linktimeoptimization"
        $content = $content -replace "enablepch", "-- enablepch"
        Set-Content garrysmod_common/premake/generator.lua -Value $content

    - name: Generate Project Files
      run: .\premake5.exe vs2022 --gmcommon=garrysmod_common

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.3

    - name: Build
      run: msbuild projects/windows/vs2022/eightbit.sln /p:Configuration=Release /p:Platform=Win32

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: gmsv_eightbit
        path: projects/windows/vs2022/x86/Release/gmsv_eightbit_win32.dll
